### ISSUE TITLE
Append to Existing Series

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#251] opened 2015-11-13 20:52 UTC
We need another 'Save' option so that users can append data to an existing series. This case would allow the user to perform QC on a new chunk of data and then append it to the end of an existing QC1 series rather than  having to re-run scripts on years of data and then write over an existing series.

This has been requested by the technicians.

**Comment by AmberSJones** [comment] 2016-01-25 14:35
Some GUI points to address:

- On the GUI page, remove the radio button by 'Save As Existing' since it is always grayed out/disabled anyway.
![image](https://cloud.githubusercontent.com/assets/5023186/12525042/a35c8086-c11e-11e5-911a-55bde58d2808.png)

- The warning that a series is being overwritten should be re-worded when append is selected. How about: "You are about to alter an existing series. This cannot be undone. Would you like to continue?"
![image](https://cloud.githubusercontent.com/assets/5023186/12552777/020aade2-c331-11e5-82b9-3b225af95c6a.png)

**Comment by AmberSJones** [comment] 2016-01-25 23:35
Re. functionality, I have had issues saving with the append option.

- When there was no data overlap, I received the below error, but apparently the dataset actually saved (I verified this):
![image](https://cloud.githubusercontent.com/assets/5023186/12553339/1db7c3c4-c334-11e5-8c11-2995c8919926.png)
![image](https://cloud.githubusercontent.com/assets/5023186/12553357/30f2dfc8-c334-11e5-864a-90d74e80548d.png)

- When there was a data overlap, I experienced the following error:
![image](https://cloud.githubusercontent.com/assets/5023186/12566672/1aecec52-c378-11e5-97a4-7e73018816f4.png)

**Comment by sreeder** [comment] 2016-04-07 22:09
The Gui issues have been fixed and applied to the append_save branch

**Comment by sreeder** [comment] 2016-04-07 22:10
the no overlap issue is being caused by the print statement to the script, after the code has run, which is why it still saves but throws an error

**Comment by sreeder** [comment] 2016-04-07 23:01
all four of the fixes are ready for testing

**Comment by horsburgh** [comment] 2016-04-26 16:08
Just tested this. The functionality seems to be working, but discovered some other issues. So, I'm going to close this one, but open another issue to cover what we discovered.

**Closed by horsburgh** 2016-04-26 16:08 UTC
Labels: feature, HighPriority, Ready for Testing

**Comment by AmberSJones** [comment] 2016-04-26 21:22
Thanks for testing this. Sorry I haven't been able to get to it!
